# Generated by Django 5.2.7 on 2025-10-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videostream_resolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.videostream')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['stream', 'name'], name='videos_vide_stream__cfcd48_idx'), models.Index(fields=['name'], name='videos_vide_name_45b08c_idx')],
                'unique_together': {('stream', 'name')},
            },
        ),
    ]
