"""Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import logging
import os
import sys
import json
from pathlib import Path


try:
    from dotenv import load_dotenv  # type: ignore

    _BASE_DIR = Path(__file__).resolve().parent.parent

    IS_PYTEST = any("pytest" in arg for arg in sys.argv)

    if IS_PYTEST and (_BASE_DIR / ".env.ci").exists():
        load_dotenv(_BASE_DIR / ".env.ci")
    elif (
        os.environ.get("ENV", "").lower() == "prod"
        and (_BASE_DIR / ".env.prod").exists()
    ):
        load_dotenv(_BASE_DIR / ".env.prod")
    elif (_BASE_DIR / ".env.dev").exists():
        load_dotenv(_BASE_DIR / ".env.dev")
except Exception:
    pass
# --- end .env loader ---


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_TEMPLATE_DIRS = [BASE_DIR / "templates"]
_accounts_templates = BASE_DIR / "accounts" / "templates"
if _accounts_templates.exists():
    PROJECT_TEMPLATE_DIRS.append(_accounts_templates)


def env(name: str, default: str | None = None):
    return os.environ.get(name, default)


def env_bool(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return str(val).lower() in {"1", "true", "yes", "on"}


def env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


def _is_blank_value(value: str | None) -> bool:
    if value is None:
        return True
    return str(value).strip().lower() in {"", "none", "null"}


def env_csv(name: str, default: str = "", allow_default: bool = True) -> list[str]:
    has_key = name in os.environ
    raw_value = os.environ.get(name) if has_key else None

    if _is_blank_value(raw_value):
        if allow_default and not has_key and not _is_blank_value(default):
            raw_value = default
        else:
            raw_value = ""

    return [part.strip() for part in str(raw_value).split(",") if part.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", "dev-secret-please-change")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)
ENV = env("ENV", "dev")
USE_SQLITE_FOR_TESTS = env_bool("USE_SQLITE_FOR_TESTS", False)
IS_TEST_ENV = ENV.lower() == "test" or USE_SQLITE_FOR_TESTS or IS_PYTEST

DEV_FRONTEND_ORIGIN = env("DEV_FRONTEND_ORIGIN", "https://videoflix.sascha-gerspach.de")
DEV_COOKIE_SAMESITE = env("DEV_COOKIE_SAMESITE", "None")
DEV_COOKIE_SECURE = env_bool("DEV_COOKIE_SECURE", True)
DEV_TLS_CERT = env("DEV_TLS_CERT", "")
DEV_TLS_KEY = env("DEV_TLS_KEY", "")
PUBLIC_MEDIA_BASE = env("PUBLIC_MEDIA_BASE", "https://videoflix.api.sascha-gerspach.de")
PUBLIC_API_BASE = env("PUBLIC_API_BASE", "https://videoflix.api.sascha-gerspach.de")

ALLOWED_HOSTS = env_csv("ALLOWED_HOSTS", default="127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = env_csv("CSRF_TRUSTED_ORIGINS", allow_default=False)
CORS_ALLOWED_ORIGINS = env_csv("CORS_ALLOWED_ORIGINS", default=DEV_FRONTEND_ORIGIN)
CORS_ALLOW_CREDENTIALS = True

# Allowed HLS renditions (env override optional)
ALLOWED_RENDITIONS = tuple(env_csv("ALLOWED_RENDITIONS", default="480p,720p,1080p"))
HLS_RENDITIONS = ALLOWED_RENDITIONS
VIDEO_ALLOWED_RENDITIONS = ALLOWED_RENDITIONS
VIDEO_RENDITIONS = ALLOWED_RENDITIONS

_AUTOTRANSCODE_POLICIES = {"relaxed", "strict", "force_1080"}


def _resolve_autotranscode_policy() -> str:
    raw = env("AUTOTRANSCODE_POLICY", "force_1080")
    if raw is None:
        return "relaxed"
    value = str(raw).strip().lower()
    if value not in _AUTOTRANSCODE_POLICIES:
        return "relaxed"
    return value


AUTOTRANSCODE_POLICY = _resolve_autotranscode_policy()


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    "accounts",
    "rest_framework",
    "corsheaders",
    "django.contrib.sites",
    "rest_framework_simplejwt",
    "videos",
    "jobs",
    "uploads",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_rq",
]

if importlib.util.find_spec("django_extensions"):
    INSTALLED_APPS += ["django_extensions"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": PROJECT_TEMPLATE_DIRS,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if USE_SQLITE_FOR_TESTS:
    # Tests / leichter Local-Run ohne PG
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "test_db.sqlite3",
        }
    }
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
else:
    # Dev/Prod aus ENV (Postgres), mit Fallback auf SQLite wenn DB_ENGINE nicht gesetzt
    engine = env("DB_ENGINE", "postgresql")
    if engine == "postgresql":
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env("DB_NAME", "videoflix"),
                "USER": env("DB_USER", "videoflix"),
                "PASSWORD": env("DB_PASSWORD", "videoflix"),
                "HOST": env("DB_HOST", "127.0.0.1"),
                "PORT": env("DB_PORT", "5432"),
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

# --- Cache Configuration ----------------------------------------------------
REDIS_URL = env("REDIS_URL", "redis://127.0.0.1:6379/1")
RQ_REDIS_URL = env("RQ_REDIS_URL", REDIS_URL)
# --- Transcode Retry/Backoff ------------------------------------------------
TRANSCODE_RETRY_MAX = env_int("TRANSCODE_RETRY_MAX", 6)
TRANSCODE_RETRY_DELAYS = [
    int(x)
    for x in env("TRANSCODE_RETRY_DELAYS", "1,2,4,8,16,32").split(",")
    if x.strip()
]
THUMB_TIMESTAMP = env("THUMB_TIMESTAMP", "00:00:03")
THUMB_WIDTH = env_int("THUMB_WIDTH", 320)
THUMB_HEIGHT = env_int("THUMB_HEIGHT", 180)
RQ_QUEUE_DEFAULT = env("RQ_QUEUE_DEFAULT", "default")
CACHE_TIMEOUT_SECONDS = env_int("CACHE_TIMEOUT_SECONDS", 300)

if IS_TEST_ENV:
    # Tests / lokale Mocks bleiben In-Memory
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "TIMEOUT": CACHE_TIMEOUT_SECONDS,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "TIMEOUT": CACHE_TIMEOUT_SECONDS,
            "KEY_PREFIX": "videoflix",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRONTEND_DOMAIN = "https://videoflix.sascha-gerspach.de"

JWT_ACCESS_LIFETIME_SECONDS = env_int("JWT_ACCESS_LIFETIME_SECONDS", 900)
JWT_REFRESH_LIFETIME_SECONDS = env_int("JWT_REFRESH_LIFETIME_SECONDS", 1209600)
JWT_LEEWAY = env_int("JWT_LEEWAY", 0)

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_PATH = env("SESSION_COOKIE_PATH", "/")
SESSION_COOKIE_DOMAIN = env("SESSION_COOKIE_DOMAIN") or None
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", ENV != "dev")

ACCESS_COOKIE_NAME = "access_token"
REFRESH_COOKIE_NAME = "refresh_token"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.domain.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/min",
        "login": "5/min",
        "transcode": "3/min",
        "video_upload": "3/min",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # "EXCEPTION_HANDLER": "rest_framework.views.exception_handler", # Standard reicht
}

REST_FRAMEWORK.update(
    {
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "EXCEPTION_HANDLER": "core.api.exception_handler.error_handler",  # unser Contract
    }
)

VIDEO_UPLOAD_MAX_BYTES = env_int("VIDEO_UPLOAD_MAX_BYTES", 2 * 1024 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = env_int(
    "DATA_UPLOAD_MAX_MEMORY_SIZE",
    1024 * 1024 * 1024,  # 1 GB
)
FILE_UPLOAD_MAX_MEMORY_SIZE = env_int(
    "FILE_UPLOAD_MAX_MEMORY_SIZE",
    DATA_UPLOAD_MAX_MEMORY_SIZE,
)

SPECTACULAR_SETTINGS = {
    "TITLE": "Videoflix API",
    "DESCRIPTION": "Videostreaming API (auth, videos, HLS).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SERVERS": [
        {"url": "http://127.0.0.1:8000", "description": "Local Dev"},
    ],
    "COMPONENTS": {
        "schemas": {
            "ErrorResponse": {
                "type": "object",
                "properties": {
                    "errors": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    }
                },
                "required": ["errors"],
                "description": "Canonical error payload with field-specific messages.",
            }
        }
    },
}

SPECTACULAR_SETTINGS.update(
    {
        "SECURITY": [{"cookieJwtAuth": []}],
    }
)

# Dev HLS bypass: nur lokal und nur in DEBUG
DEV_HLS_AUTH_BYPASS = env_bool("DEV_HLS_AUTH_BYPASS", False)

RQ_URL = env("RQ_URL", "redis://127.0.0.1:6379/0")
RQ_QUEUE_TRANSCODE = (env("RQ_QUEUE_TRANSCODE", "transcode") or "").strip()

RQ_QUEUES: dict[str, dict[str, int]] = {}
if RQ_QUEUE_TRANSCODE:
    RQ_QUEUES[RQ_QUEUE_TRANSCODE] = {
        "URL": RQ_URL,
        "DEFAULT_TIMEOUT": 60 * 20,
    }


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "WARNING"},
        "videoflix": {"handlers": ["console"], "level": "INFO"},
    },
}

if DEBUG:
    logging.getLogger("videoflix").info("ALLOWED_RENDITIONS=%s", ALLOWED_RENDITIONS)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
PUBLIC_MEDIA_BASE = env("PUBLIC_MEDIA_BASE", "https://videoflix.api.sascha-gerspach.de")

VIDEO_RUNG_RULES_DEFAULT = {
    "1080p": {"min_height": 1080, "min_total_kbps": 3500},
    "720p": {"min_height": 720, "min_total_kbps": 1800},
    "480p": {"min_height": 1, "min_total_kbps": 0},
}


def _load_rung_rules():
    raw = os.environ.get("VIDEO_RUNG_RULES")
    if not raw:
        return VIDEO_RUNG_RULES_DEFAULT
    try:
        data = json.loads(raw)
        # sehr defensive Normalisierung
        rules = {
            k: {
                "min_height": int(v.get("min_height", 0)),
                "min_total_kbps": int(v.get("min_total_kbps", 0)),
            }
            for k, v in data.items()
        }
        return rules or VIDEO_RUNG_RULES_DEFAULT
    except Exception:
        return VIDEO_RUNG_RULES_DEFAULT


VIDEO_RUNG_RULES = _load_rung_rules()

# --- Rendition Thresholds ---------------------------------------------------
TRANSCODE_ENABLE_720_MIN_SRC_HEIGHT = env_int(
    "TRANSCODE_ENABLE_720_MIN_SRC_HEIGHT", 700
)
TRANSCODE_ENABLE_720_MIN_SRC_BITRATE = env_int(
    "TRANSCODE_ENABLE_720_MIN_SRC_BITRATE", 2_500_000
)
TRANSCODE_ENABLE_1080_MIN_SRC_HEIGHT = env_int(
    "TRANSCODE_ENABLE_1080_MIN_SRC_HEIGHT", 1000
)
TRANSCODE_ENABLE_1080_MIN_SRC_BITRATE = env_int(
    "TRANSCODE_ENABLE_1080_MIN_SRC_BITRATE", 4_500_000
)

# Email configuration
# supports "smtp", "console", "locmem"
EMAIL_BACKEND_NAME = env("EMAIL_BACKEND", "").lower()
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", "Videoflix <noreply@example.com>")
SERVER_EMAIL = env("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = env("EMAIL_SUBJECT_PREFIX", "[Videoflix] ")

if EMAIL_BACKEND_NAME == "smtp" or ENV == "prod":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    # e.g. "smtp.mailprovider.com"
    EMAIL_HOST = env("EMAIL_HOST", "")
    EMAIL_PORT = env_int("EMAIL_PORT", 587)  # 587 = TLS, 465 = SSL
    # e.g. "noreply@example.com"
    EMAIL_HOST_USER = env("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)  # True for port 587
    # Port 465 prefers SSL instead of TLS
    EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
elif EMAIL_BACKEND_NAME == "locmem":
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
else:
    # Development default: log e-mails to stdout
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Public-facing frontend URL base
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "https://videoflix.app")


SITE_ID = int(env("SITE_ID", 1))
